spring.datasource.url=${MED_OFFICE_DB_URL:jdbc:mysql://127.0.0.1:3306/med_office?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${MED_OFFICE_DB_USERNAME:med_office}
spring.datasource.password=${MED_OFFICE_DB_PASSWORD:change_me}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
